services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ecommerce
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build: .
    environment:
      - NODE_ENV=production
      - DB_HOST=db
      - DB_USER=postgres
      - DB_PASS=postgres
      - DB_NAME=ecommerce
      - JWT_SECRET=supersecret
      - PORT=50051
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "50051:50051"
    command: >
      sh -c "npx sequelize-cli db:migrate && node src/server.js"

volumes:
  db_data:
